name: Using hello world
on: [push]

jobs:
  hello_world_job:
    runs-on: [ubuntu-latest, macos-latest, windows-latest]
    name: A job to say hello
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello world action step
        uses: ULL-ESIT-PL-2021/hello-js-action-alu0101048239@v2
        id: hello
        with:
          who-to-greet: 'David Hernandez Suarez'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"